### ISSUE TITLE
When starting Mininet, pingall does not succeed.

### ISSUE THREAD

**Issue by zhangxianghao** [assyafii/ONOS-P4-INT#1]
Are you experiencing this problem? Do you have a good solution?
The host can ping the switch, but the host cannot be pinged.
<img width="1279" alt="联想截图_20230322012302" src="https://user-images.githubusercontent.com/59169258/226691611-00a1199e-c941-4330-9187-df3c16bde1ef.png">
![K@39C43{40ZU}AKGNX%6SN9](https://user-images.githubusercontent.com/59169258/226691750-c27ada16-3e84-4954-89ba-665d8c84d054.jpg)

**Comment by assyafii** [comment]
Hello @zhangxianghao have you enabled **reactive forwarding** feature on onos dashboard ?

**Comment by assyafii** [comment]
you can check on my documentation https://luthfi.dev/posts/lab-p4-int-in-band-network-telemetry-with-onos-from-scratch/

**Comment by assyafii** [comment]
Any update for this issue ? @zhangxianghao

**Comment by zhangxianghao** [comment]
Hello, I've solved the problem. This problem arises when I install mininet with an error.
